# Generated by Django 4.0.1 on 2022-11-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='type',
            field=models.CharField(default='PRIVATE LTD', max_length=15),
            preserve_default=False,
        ),
    ]
