# Generated by Django 4.0.1 on 2022-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='ocr_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='reg_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('PENDING APPROVAL', 'Pending Approval')], max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('PVT LTD', 'Pvt Ltd'), ('Domestic', 'Domestic'), ('Others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='ward_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
