# Generated by Django 4.0.1 on 2022-11-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_business_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessownerrelation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owners', to='core.business'),
        ),
    ]
