# Generated by Django 4.0.1 on 2022-11-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_businessownerrelation_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='businessownerdetail',
            name='address_street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='businessownerdetail',
            name='temp_address_street',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
