# Generated by Django 4.0.1 on 2022-11-28 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_business_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
