# Generated by Django 4.0.1 on 2022-12-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_business_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='first_name',
            field=models.CharField(default='a', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='land_ownership_certificate',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='last_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='middle_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
